apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    storage "raft" {
      path = "/vault/data"
      node_id = "$HOSTNAME"
    }
    
    listener "tcp" {
      address       = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_cert_file = "/vault/tls/server.crt"
      tls_key_file  = "/vault/tls/server.key"
    }
    
    disable_mlock = true
    api_addr = "https://$HOSTNAME.vault.vault.svc.cluster.local:8200"
    cluster_addr = "https://$HOSTNAME.vault.vault.svc.cluster.local:8201"
    ui = true