- name: check or install python3 and pip
  hosts: localhost
  become: no
  tasks:
    - name: check python3 
      command: python3 --version
      ignore_errors: yes
      register: python3_version
    
    - name: show python3 version
      debug:
        msg: "python3 version is {{ python3_version.stdout }}"
      when:
        python3_version.stdout | length > 0
    
    - name: python3 install
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes
      become: yes
      when: python3_version.stdout | length == 0
    
    - name: pip install for flask
      apt:
        name: python3-pip
        update_cache: yes
      become: yes
      when: python3_version.stdout | length > 0