---
- name: Install Docker on Rocky Linux 9
  hosts: ansible-3
  become: yes
  vars:
    docker_repo_url: "https://download.docker.com/linux/centos/docker-ce.repo"

  tasks:
    - name: Ensure dnf-plugins-core is installed
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker repository
      command: dnf config-manager --add-repo {{ docker_repo_url }}
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker and related packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Enable and start containerd service
      systemd:
        name: containerd
        enabled: yes
        state: started