pipeline {
    agent any
    tools {
        jdk 'JDK-21'
        nodejs 'NODE-18'
    }
    environment {
        DOCKER_IMAGE='simple-react-app'
    }
    options {
        timeout(time:30, unit:'MINUTES')
    }
    stages {
        stage('OS Check'){
            steps{
                sh "cat /etc/os-release | sed -n 's/^PRETTY_NAME=\"\\(.*\\)\"/\\1/p'"
            }
        }
        stage('Software Check'){
            steps{
                sh '''
                    echo $(node -v)
                    echo $(java -version 2>&1 | sed -n '1p')
                    echo
                '''
            }
        }
        stage('Run Docker Check'){
            steps{
                script{
                    def dockerVersion = sh(script: '''
                        chmod +x check_docker.sh
                        bash check_docker.sh
                    ''', returnStdout: true).trim()
                    
                    echo "$dockerVersion"
                }
            }
        }
        stage('Clean Workspace'){
            steps{
                cleanWs()
            }
        }
    }
}