pipeline {
    agent any
    tools {
        jdk 'JDK-21'
        nodejs 'NODE-18'
    }
    environment {
        DOCKER_IMAGE='simple-react-app'
    }
    options {
        timeout(time:30, unit:'MINUTES')
    }
    stages {
        // stage('Clean Workspace'){
        //     steps{
        //         cleanWs()
        //     }
        // }
        stage('OS Check'){
            steps{
                sh "cat /etc/os-release | sed -n 's/^PRETTY_NAME=\"\\(.*\\)\"/\\1/p'"
                sh "hostnamectl | awk NR==7"
            }
        }
        stage('Software Check'){
            steps{
                sh '''
                    echo $(node -v)
                    echo $(java -version 2>&1 | sed -n '1p')
                '''
            }
        }
        stage('Docker Version') {
            steps {
                script {
                    
                    sh 'ls -la'

                    sh 'ls -la ci-cd/jenkins-infra-aws/'

                    if (fileExists('ci-cd/jenkins-infra-aws/docker_version.sh')) {
                        
                        sh 'chmod +x ci-cd/jenkins-infra-aws/docker_version.sh'

                        sh 'ci-cd/jenkins-infra-aws/docker_version.sh'
                    } else {
                        error("docker_version.sh not found in the workspace!")
                    }
                }
             }
        }
        stage('Docker System Cleanup'){
            steps{
                sh '''
                    docker system prune -a -f --volumes || true
                    if docker images ${DOCKER_IMAGES} -q | grep -q .;then
                        docker rmi $(docker images ${DOCKER_IMAGE} -q) || true
                    fi
                '''
            }
        }
        stage('Checkout form Git'){
            steps{
                git branch: 'main', url:'https://github.com/amirul1994/devops.git'
            }
        }
        stage('Install Dependencies'){
            steps{
                dir('ci-cd/jenkins-infra-aws/simple-react-app'){
                    sh """
                        npm cache clean --force
                        rm -rf node_modules package-lock.json
                        npm install
                    """
                }
            }
        }
        stage('Docker Build & Push'){
            steps{
                script{
                    try{
                        def imageTag="${BUILD_NUMBER}"
                        def fullImageName = "amirul1994/${DOCKER_IMAGE}:${imageTag}"

                        // echo "DOCKER_IMAGE: ${DOCKER_IMAGE}"
                        // echo "BUILD_NUMBER: ${BUILD_NUMBER}"
                        // echo "Full Image Name: ${fullImageName}"

                        dir('ci-cd/jenkins-infra-aws/simple-react-app'){
                            withDockerRegistry([credentialsId:'dockerhub-credentials', url: '', toolName:'Docker']){
                                sh """
                                    docker build --no-cache -t ${fullImageName} . || (echo 'Docker build failed' && exit 1)
                                    docker push ${fullImageName} || (echo 'Docker push failed' && exit 1) 
                                """
                            }
                        }
                    }catch (Exception e){
                        echo "Docker build or push failed: ${e.getMessage()}"
                        throw e
                    }
                }
            }
        }
    }
}