# Generated by Django 5.0.4 on 2024-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('age', models.TextField(max_length=4)),
                ('profession', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
