DROP DATABASE IF EXISTS userdb; 

CREATE DATABASE userdb;

CREATE USER IF NOT EXISTS 'amirul'@'%' IDENTIFIED WITH mysql_native_password BY 'Tfgh&*123#';

GRANT ALL PRIVILEGES ON userdb.* TO 'amirul'@'%';

FLUSH PRIVILEGES;

USE userdb;

CREATE TABLE IF NOT EXISTS userinfo (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NULL,
age INT(4) NULL, profession VARCHAR(50) NULL, address VARCHAR(100) NULL, password VARCHAR(128) NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
