- name: check or install nodejs
  hosts: localhost
  become: no
  tasks:
    - name: check nodejs version
      command: node --version
      register: node_version
      ignore_errors: yes
      
    - name: show nodejs version
      debug:
        msg: "NodeJS version is {{ node_version.stdout }}"
      when: node_version.stdout | length > 0
    
    - name: install nodejs if not installed
      block:
        - name: install nvm
          shell: >
            wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        
        - name: downloaded directory
          command: pwd
          register: download_directory

        - name: show download directory
          debug:
            msg: "{{ download_directory.stdout }}"
          
        - name: change permission of install.sh
          become: yes
          file:
            path: "{{ download_directory.stdout }}/install.sh"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0700'

        - name: install nvm
          shell: 
            bash "{{ download_directory.stdout }}/install.sh"
          args:
            executable: /bin/bash
        
        - name: install nodejs
          shell: >
            source "{{ download_directory.stdout }}/.nvm/nvm.sh" && nvm install 18
          args:
            executable: /bin/bash
          become: yes
          
      when: node_version.stdout | length == 0

- name: check or install python3 for flask
  hosts: localhost
  become: no
  tasks:
    - name: check python3 
      command: python3 --version
      ignore_errors: yes
      register: python3_version
    
    - name: show python3 version
      debug:
        msg: "python3 version is {{ python3_version.stdout }}"
      when:
        python3_version.stdout | length > 0
    
    - name: python3 install
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes
      become: yes
      when: python3_version.stdout | length == 0

- name: check or install java and springboot
  hosts: localhost
  become: no
  tasks:
    - name: check java version
      shell: >
        java --version | awk 'NR==1'
      register: java_version
      ignore_errors: yes
      args:
        executable: /bin/bash 
    
    - name: show java version or install java
      block:
        - name: show java version
          debug:
            msg: "Java version is {{ java_version.stdout }}" 
          when: java_version.stdout | length > 0
        
        - name: install java
          apt:
            name: openjdk-21-jdk
            update_cache: yes
          when: java_version.stdout | length == 0

