- name: check or install nodejs
  hosts: localhost
  become: no
  tasks:
    - name: check nodejs version
      command: node --version
      register: node_version
      ignore_errors: yes
      
    - name: show nodejs version
      debug:
        msg: "NodeJS version is {{ node_version.stdout }}"
      when: node_version.stdout | length > 0
    
    - name: install nodejs if not installed
      block:
        - name: install nvm
          shell: >
            wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        
        - name: downloaded directory
          command: pwd
          register: download_directory

        - name: show download directory
          debug:
            msg: "{{ download_directory.stdout }}"
          
        - name: change permission of install.sh
          become: yes
          file:
            path: "{{ download_directory.stdout }}/install.sh"
            owner: "{{ ansible_env.USER }}"
            group: "{{ ansible_env.USER }}"
            mode: '0700'

        - name: install nvm
          shell: 
            bash "{{ download_directory.stdout }}/install.sh"
          args:
            executable: /bin/bash
        
        - name: install nodejs
          shell: >
            source "{{ download_directory.stdout }}/.nvm/nvm.sh" && nvm install 18
          args:
            executable: /bin/bash
          become: yes
          
      when: node_version.stdout | length == 0