apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tol-dep
  labels:
    type: web-srv
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web-srv
  template:
    metadata:
      labels:
        type: web-srv
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "blue"
        effect: "NoSchedule"  
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
