apiVersion: v1
kind: Pod
metadata:
  name: static-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    # place this file in /etc/kubernetes/mainfests/
    # otherwise it won't work as static pod