apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "echo Init container is running! && sleep 5"]
  containers:
  - name: container-1
    image: busybox
    command: ["sh", "-c", "echo container 1 is running! && sleep 3600"]
  - name: container-2
    image: busybox
    command: ["sh", "-c", "echo container 2 is running! && sleep 3600"]