apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels: 
    type: nfs
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.50
    path: "/mnt/lvm_storage/devops/for_kube_pv"