apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8080"
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 32000
  selector:
    app: jenkins-server