apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner  # Replace with your provisioner (e.g., kubernetes.io/aws-ebs)
volumeBindingMode: WaitForFirstConsumer
