- name: Install apache web server
  hosts: webservers
  become: yes
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
