- name: Install apache web server
  hosts: servers
  become: yes
  tasks:
    - name: Install apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
