- name: iptables rule creation
  hosts: servers
  become: Yes
  tasks:
    - name: iptables rule creation linux
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
        state: present