- name: gather facts about hosts
  hosts: all
  gather_facts: yes
  tasks:
    - name: display os family
      debug:
        msg: "the os family is {{ ansible_os_family }}"

    - name: os info
      shell: cat /etc/os-release
      register: os_release_contents

    - name: print os info
      debug:
        var: os_release_contents.stdout      